title: Data Processing Lab Notebook
email: arbox@yandex.com
description: > # this means to ignore newlines until "baseurl:"
  Frontiers of Data Processing, Language Engineering and Mashine
  Learning in Ruby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bu.chsta.be" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nonwebruby
github_username:  arbox

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - mkdocs.yml
  - _site
  - _site_source
  - _mkdocs_source
source: source
destination: public
permalink: /notebook/:year/:month/:title.html
keep_files:
  - CNAME
  - .git
yandex_metrica: true
